### ISSUE TITLE
H index non-monotonous

### ISSUE THREAD

**Issue by davidwozabal** [boz1/tum-scopus-project#22]
The h-index of departments is non-monotonous. 

Selecting all departments yields a h-index of 7.1111 for the finance and accounting department in Jun-19 and an h-index of 6.75 in Jul-19.

This can not be, since citations do not go away -> number of citations increases with time -> h-index increases with time.

**Comment by boz1** [comment]
I assume this issue is fixed for now, regarding all the h-index are 7 when finance and accounting dep. is selected. On the other hand, since our API is not working since mid July, we are actually missing some data for most of the authors. So if there is a decrease on July (in other statistics as well), thats because we don't have the data.

**Comment by nicknn7** [comment]
I assume this issue is fixed for now, regarding all the h-index are 7 when finance and accounting dep. is selected. 

> On the other hand, since our API is not working since mid July, we are actually missing some data for most of the authors. So if there is a decrease on July (in other statistics as well), thats because we don't have the data.

I guess we should define it s.t. if data is unavailable, there should be NA, not a decrease

**Comment by nicknn7** [comment]
The h-index and the citations are monotonous, the only exception is the last month. Reason: Data can be unavailable before the month is completed for a certain author. if you then build the sum, some terms in the sum are missing -> the value decreases. We will fix this by substituting the last available value for the calculation of the sum.

**Comment by boz1** [comment]
issue resolved now
